Importing the libraries

In [2]:
pip install numpy

   ---------------------------------------- 0.0/12.7 MB ? eta -:--:--
    --------------------------------------- 0.3/12.7 MB ? eta -:--:--
   - -------------------------------------- 0.5/12.7 MB 1.5 MB/s eta 0:00:09
   -- ------------------------------------- 0.8/12.7 MB 1.4 MB/s eta 0:00:09
   --- ------------------------------------ 1.0/12.7 MB 1.5 MB/s eta 0:00:08
   ---- ----------------------------------- 1.3/12.7 MB 1.3 MB/s eta 0:00:10
   ----- ---------------------------------- 1.8/12.7 MB 1.4 MB/s eta 0:00:08
   ------ --------------------------------- 2.1/12.7 MB 1.6 MB/s eta 0:00:07
   --------- ------------------------------ 2.9/12.7 MB 1.7 MB/s eta 0:00:06
   --------- ------------------------------ 2.9/12.7 MB 1.7 MB/s eta 0:00:06
   --------- ------------------------------ 3.1/12.7 MB 1.5 MB/s eta 0:00:07
   ----------- ---------------------------- 3.7/12.7 MB 1.6 MB/s eta 0:00:06
   ------------- -------------------------- 4.2/12.7 MB 1.7 MB/s eta 0:00:06
   ----------

  Consider adding this directory to PATH or, if you prefer to suppress this warning, use --no-warn-script-location.

[notice] A new release of pip is available: 25.0.1 -> 25.1.1
[notice] To update, run: python.exe -m pip install --upgrade pip


In [5]:
pip install matplotlib

   ---------------------------------------- 0.0/8.1 MB ? eta -:--:--
   - -------------------------------------- 0.3/8.1 MB ? eta -:--:--
   -- ------------------------------------- 0.5/8.1 MB 1.6 MB/s eta 0:00:05
   ----- ---------------------------------- 1.0/8.1 MB 1.6 MB/s eta 0:00:05
   ----- ---------------------------------- 1.0/8.1 MB 1.6 MB/s eta 0:00:05
   ------- -------------------------------- 1.6/8.1 MB 1.5 MB/s eta 0:00:05
   --------- ------------------------------ 1.8/8.1 MB 1.7 MB/s eta 0:00:04
   ----------- ---------------------------- 2.4/8.1 MB 1.6 MB/s eta 0:00:04
   ----------- ---------------------------- 2.4/8.1 MB 1.6 MB/s eta 0:00:04
   ----------- ---------------------------- 2.4/8.1 MB 1.6 MB/s eta 0:00:04
   ------------ --------------------------- 2.6/8.1 MB 1.2 MB/s eta 0:00:05
   ------------ --------------------------- 2.6/8.1 MB 1.2 MB/s eta 0:00:05
   ------------ --------------------------- 2.6/8.1 MB 1.2 MB/s eta 0:00:05
   ------------ ----------

  Consider adding this directory to PATH or, if you prefer to suppress this warning, use --no-warn-script-location.

[notice] A new release of pip is available: 25.0.1 -> 25.1.1
[notice] To update, run: python.exe -m pip install --upgrade pip


In [6]:
pip install pandas

   ---------------------------------------- 0.0/11.0 MB ? eta -:--:--
    --------------------------------------- 0.3/11.0 MB ? eta -:--:--
   - -------------------------------------- 0.5/11.0 MB 1.4 MB/s eta 0:00:08
   - -------------------------------------- 0.5/11.0 MB 1.4 MB/s eta 0:00:08
   -- ------------------------------------- 0.8/11.0 MB 920.7 kB/s eta 0:00:12
   -- ------------------------------------- 0.8/11.0 MB 920.7 kB/s eta 0:00:12
   -- ------------------------------------- 0.8/11.0 MB 920.7 kB/s eta 0:00:12
   --- ------------------------------------ 1.0/11.0 MB 704.7 kB/s eta 0:00:15
   --- ------------------------------------ 1.0/11.0 MB 704.7 kB/s eta 0:00:15
   ---- ----------------------------------- 1.3/11.0 MB 614.5 kB/s eta 0:00:16
   ---- ----------------------------------- 1.3/11.0 MB 614.5 kB/s eta 0:00:16
   ---- ----------------------------------- 1.3/11.0 MB 614.5 kB/s eta 0:00:16
   ----- ---------------------------------- 1.6/11.0 MB 560.5 kB/s eta 0:0


[notice] A new release of pip is available: 25.0.1 -> 25.1.1
[notice] To update, run: python.exe -m pip install --upgrade pip


In [7]:
import numpy as np
import matplotlib.pyplot as plt
import pandas as pd

Importing the dataset

In [8]:
dataset = pd.read_csv('./Data/Data.csv')
X = dataset.iloc[:, :-1].values
y = dataset.iloc[:, -1].values

In [9]:
print(X)
print(y)

[['France' 44.0 72000.0]
 ['Spain' 27.0 48000.0]
 ['Germany' 30.0 54000.0]
 ['Spain' 38.0 61000.0]
 ['Germany' 40.0 nan]
 ['France' 35.0 58000.0]
 ['Spain' nan 52000.0]
 ['France' 48.0 79000.0]
 ['Germany' 50.0 83000.0]
 ['France' 37.0 67000.0]]
['No' 'Yes' 'No' 'No' 'Yes' 'Yes' 'No' 'Yes' 'No' 'Yes']


Taking care of missing data

In [18]:
pip install scikit-learn

   ---------------------------------------- 0.0/10.7 MB ? eta -:--:--
   ---- ----------------------------------- 1.3/10.7 MB 7.6 MB/s eta 0:00:02
   ----------- ---------------------------- 3.1/10.7 MB 8.0 MB/s eta 0:00:01
   --------------- ------------------------ 4.2/10.7 MB 7.5 MB/s eta 0:00:01
   ---------------------- ----------------- 6.0/10.7 MB 7.5 MB/s eta 0:00:01
   ----------------------------- ---------- 7.9/10.7 MB 7.9 MB/s eta 0:00:01
   ---------------------------------- ----- 9.2/10.7 MB 7.5 MB/s eta 0:00:01
   ---------------------------------------  10.5/10.7 MB 7.8 MB/s eta 0:00:01
   ---------------------------------------- 10.7/10.7 MB 7.0 MB/s eta 0:00:00
   ---------------------------------------- 0.0/38.4 MB ? eta -:--:--
   - -------------------------------------- 1.0/38.4 MB 5.6 MB/s eta 0:00:07
   -- ------------------------------------- 2.4/38.4 MB 6.4 MB/s eta 0:00:06
   ---- ----------------------------------- 3.9/38.4 MB 7.2 MB/s eta 0:00:05
   ------ -


[notice] A new release of pip is available: 25.0.1 -> 25.1.1
[notice] To update, run: python.exe -m pip install --upgrade pip


In [19]:
from sklearn.impute import SimpleImputer
imputer = SimpleImputer(missing_values=np.nan, strategy='mean')
imputer.fit(X[:, 1:3])
X[:, 1:3] = imputer.transform(X[:, 1:3])

In [20]:
print(X)

[['France' 44.0 72000.0]
 ['Spain' 27.0 48000.0]
 ['Germany' 30.0 54000.0]
 ['Spain' 38.0 61000.0]
 ['Germany' 40.0 63777.77777777778]
 ['France' 35.0 58000.0]
 ['Spain' 38.77777777777778 52000.0]
 ['France' 48.0 79000.0]
 ['Germany' 50.0 83000.0]
 ['France' 37.0 67000.0]]


Encoding categorical data

In [22]:
#Encoding the Independent Variable
from sklearn.compose import ColumnTransformer
from sklearn.preprocessing import OneHotEncoder
ct = ColumnTransformer(transformers=[('encoder', OneHotEncoder(), [0])], remainder='passthrough')
X = np.array(ct.fit_transform(X))

In [23]:
print(X)

[[0.0 1.0 0.0 0.0 44.0 72000.0]
 [1.0 0.0 0.0 1.0 27.0 48000.0]
 [1.0 0.0 1.0 0.0 30.0 54000.0]
 [1.0 0.0 0.0 1.0 38.0 61000.0]
 [1.0 0.0 1.0 0.0 40.0 63777.77777777778]
 [0.0 1.0 0.0 0.0 35.0 58000.0]
 [1.0 0.0 0.0 1.0 38.77777777777778 52000.0]
 [0.0 1.0 0.0 0.0 48.0 79000.0]
 [1.0 0.0 1.0 0.0 50.0 83000.0]
 [0.0 1.0 0.0 0.0 37.0 67000.0]]


In [24]:
#Encoding the Dependent Variable
from sklearn.preprocessing import LabelEncoder
le = LabelEncoder()
y = le.fit_transform(y)

In [25]:
print(y)

[0 1 0 0 1 1 0 1 0 1]


Splitting the dataset into the Training set and Test set

In [26]:
from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size = 0.2, random_state = 1)

In [27]:
print(X_train)

[[1.0 0.0 0.0 1.0 38.77777777777778 52000.0]
 [1.0 0.0 1.0 0.0 40.0 63777.77777777778]
 [0.0 1.0 0.0 0.0 44.0 72000.0]
 [1.0 0.0 0.0 1.0 38.0 61000.0]
 [1.0 0.0 0.0 1.0 27.0 48000.0]
 [0.0 1.0 0.0 0.0 48.0 79000.0]
 [1.0 0.0 1.0 0.0 50.0 83000.0]
 [0.0 1.0 0.0 0.0 35.0 58000.0]]


In [29]:
print(X_test)

[[1.0 0.0 1.0 0.0 30.0 54000.0]
 [0.0 1.0 0.0 0.0 37.0 67000.0]]


In [30]:
print(y_train)

[0 1 0 0 1 1 0 1]


In [31]:
print(y_test)

[0 1]


Feature Scaling

In [32]:
from sklearn.preprocessing import StandardScaler
sc = StandardScaler()
X_train = sc.fit_transform(X_train)
X_test = sc.transform(X_test)

In [33]:
print(X_train)

[[ 0.77459667 -0.77459667 -0.57735027  1.29099445 -0.19159184 -1.07812594]
 [ 0.77459667 -0.77459667  1.73205081 -0.77459667 -0.01411729 -0.07013168]
 [-1.29099445  1.29099445 -0.57735027 -0.77459667  0.56670851  0.63356243]
 [ 0.77459667 -0.77459667 -0.57735027  1.29099445 -0.30453019 -0.30786617]
 [ 0.77459667 -0.77459667 -0.57735027  1.29099445 -1.90180114 -1.42046362]
 [-1.29099445  1.29099445 -0.57735027 -0.77459667  1.14753431  1.23265336]
 [ 0.77459667 -0.77459667  1.73205081 -0.77459667  1.43794721  1.57499104]
 [-1.29099445  1.29099445 -0.57735027 -0.77459667 -0.74014954 -0.56461943]]


In [34]:
print(X_test)

[[ 0.77459667 -0.77459667  1.73205081 -0.77459667 -1.46618179 -0.9069571 ]
 [-1.29099445  1.29099445 -0.57735027 -0.77459667 -0.44973664  0.20564034]]
